const cfg = {id:null, detail:null, tab:'inbounds', index:0, add:false, preview:null, request:null, version:0};
const cfgTabs = [['inbounds','入站'],['outbounds','出站'],['routes','路由'],['clients','用户'],['maintenance','维护']];
const cfgFields = [['domain_suffix','域名后缀'],['domain','完整域名'],['domain_keyword','域名关键词'],['ip_cidr','IP 网段'],['port','目标端口'],['protocol','协议'],['inbound','入站 Tag'],['auth_user','用户名称'],['rule_set','规则集'],['source_ip_cidr','来源 IP'],['network','网络']];
const cfgList = () => cfg.tab==='inbounds'?cfg.detail?.inbounds?.inbounds||[]:cfg.tab==='outbounds'?cfg.detail?.outbounds?.outbounds||[]:cfg.tab==='routes'?cfg.detail?.route_rules||[]:cfg.tab==='clients'?cfg.detail?.clients?.clients||[]:[];
const cfgCurrent = () => cfgList()[cfg.index];
const cfgField = key => document.querySelector(`#config-workspace [data-cfg="${key}"]`);
const cfgValue = key => cfgField(key)?.value.trim()||'';
const cfgInput = (label,key,value='',type='text') => `<label>${esc(label)}<input data-cfg="${key}" type="${type}" value="${esc(value??'')}" ${type==='number'?'min="1" max="65535"':''}></label>`;
const cfgSelect = (label,key,options,value) => `<label>${esc(label)}<select data-cfg="${key}">${options.map(([k,v])=>`<option value="${esc(k)}" ${String(k)===String(value)?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`;
const cfgPort = (key,required=false) => {const s=cfgValue(key);if(!s&&!required)return 0;const n=Number(s);if(!Number.isInteger(n)||n<1||n>65535)throw Error(`${key} 须为 1–65535`);return n};
const cfgRequired = (key,label) => {const v=cfgValue(key);if(!v)throw Error(`请填写${label}`);return v};
const cfgRedact = obj => Array.isArray(obj)?obj.map(cfgRedact):obj&&typeof obj==='object'?Object.fromEntries(Object.entries(obj).map(([k,v])=>[k,/password|secret|private_key|token/i.test(k)?'••••••':cfgRedact(v)])):obj;
function cfgResetPreview(){cfg.version++;cfg.preview=null;cfg.request=null;$('config-preview')?.remove()}
function cfgTabFromAction(action){return action.startsWith('inbound_')?'inbounds':action.startsWith('outbound_')?'outbounds':action.startsWith('route_')?'routes':action.startsWith('client_')?'clients':'maintenance'}
async function openSingleEditor(serverID,action='inbound_patch',target=''){
  const server=state.servers.find(x=>x.id===+serverID);if(!server)return;
  if($('detail-dialog').open)$('detail-dialog').close();
  cfg.id=server.id;cfg.detail=null;cfg.tab=cfgTabFromAction(action);cfg.add=action.endsWith('_create')||action.endsWith('_add');cfg.index=0;cfgResetPreview();
  $('editor-title').textContent=server.name;$('config-subtitle').textContent='正在读取 S-UI 配置…';$('config-workspace').innerHTML='<p class="muted">正在读取当前配置…</p>';
  if(!$('single-editor-dialog').open)$('single-editor-dialog').showModal();
  try{const d=await api(`servers/${server.id}/detail`);if(cfg.id!==server.id||!$('single-editor-dialog').open)return;cfg.detail=d;
    if(target!==''&&!cfg.add){const i=cfg.tab==='routes'?Number(target):cfgList().findIndex(x=>(x.tag||x.name)===target);if(i>=0&&i<cfgList().length)cfg.index=i;}
    $('config-subtitle').textContent=`${server.region||'未分组'} · 选择对象后直接编辑`;cfgRender();
  }catch(e){$('config-workspace').innerHTML=`<p class="error">读取失败：${esc(e.message)}</p>`}
}
function cfgSection(title,subtitle,content,preview=true){return `<div class="config-work-head"><div class="eyebrow">${esc(cfgTabs.find(x=>x[0]===cfg.tab)?.[1]||'')}</div><h3>${esc(title)}</h3><p>${esc(subtitle)}</p></div><div class="config-form">${content}</div>${preview?'<div class="config-submit"><button id="config-preview-button" class="primary">预览变更</button></div>':''}`}
function cfgRender(){
  const items=cfgList();$('config-tabs').innerHTML=cfgTabs.map(([key,label])=>`<button data-cfg-tab="${key}" class="${cfg.tab===key?'active':''}" aria-selected="${cfg.tab===key}">${label}<span>${key==='maintenance'?'':key==='routes'?(cfg.detail.route_rules||[]).length:key==='inbounds'?(cfg.detail.inbounds?.inbounds||[]).length:key==='outbounds'?(cfg.detail.outbounds?.outbounds||[]).length:(cfg.detail.clients?.clients||[]).length}</span></button>`).join('');
  $('config-list-title').textContent=cfgTabs.find(x=>x[0]===cfg.tab)?.[1];$('config-add').classList.toggle('hidden',cfg.tab==='maintenance');$('config-add').textContent='＋ 新增'+(cfg.tab==='routes'?'规则':cfg.tab==='inbounds'?'入站':cfg.tab==='outbounds'?'出站':'用户');
  $('config-list').innerHTML=items.map((x,i)=>`<button data-cfg-index="${i}" class="config-object ${!cfg.add&&cfg.index===i?'active':''}"><span>${cfg.tab==='routes'?`<b class="rule-index">${i+1}</b>`:''}${esc(cfg.tab==='routes'?x.outbound||x.action||'规则':x.tag||x.name||'未命名')}</span><small>${esc(cfg.tab==='routes'?Object.keys(x).filter(k=>!['action','outbound'].includes(k)).join(' · ')||'无匹配条件':cfg.tab==='inbounds'?`${x.type} · ${x.listen_port||'—'}`:cfg.tab==='outbounds'?x.type:x.enable?'已启用':'已停用')}</small></button>`).join('')||'<div class="config-empty">暂无对象。点击上方新增。</div>';
  $('config-workspace').innerHTML=cfg.add?cfgCreate():cfg.tab==='maintenance'?cfgSection('维护操作','修改写入前会自动备份数据库。','<div class="config-action-pair"><button data-cfg-action="backup" class="secondary">备份数据库</button><button data-cfg-action="restartSb" class="secondary">重启 sing-box</button></div>',false):items.length?cfgEdit():cfgSection('选择配置','从左侧选择对象或新增。','',false);
  cfgResetPreview();cfgVisibility();
}
function cfgEdit(){const x=cfgCurrent();
  if(cfg.tab==='inbounds'){const pub=x.addrs?.[0]||x.out_json||{};return cfgSection(x.tag,`${x.type} · 入站 #${x.id}`,`<div class="config-fields">${cfgInput('监听地址','listen',x.listen||'')}${cfgInput('监听端口','listen_port',x.listen_port,'number')}${cfgInput('订阅公开地址','public_server',pub.server||'')}${cfgInput('订阅公开端口','public_port',pub.server_port||'','number')}</div><p class="hint">协议、TLS、传输设置与用户会保留。</p>${cfgExisting(x)}`)}
  if(cfg.tab==='outbounds'){const special=['direct','block'].includes(x.type),udp=x.udp_over_tcp,uv=udp===true?'2':udp?.enabled?String(udp.version||2):'off';return cfgSection(x.tag,`${x.type} · 出站 #${x.id}`,`${special?'<p class="hint">此内置出站没有远端参数。</p>':`<div class="config-fields">${cfgInput('远端服务器','server',x.server||'')}${cfgInput('远端端口','server_port',x.server_port||'','number')}${['socks','http','vless'].includes(x.type)?cfgInput(x.type==='vless'?'UUID':'用户名','user',x.type==='vless'?x.uuid:x.username||''):''}${['socks','http','trojan','hysteria2','anytls'].includes(x.type)?cfgInput('新密码（留空保留）','password','','password'):''}${x.type==='socks'?cfgSelect('UDP over TCP','udp',[['off','禁用'],['2','启用 · 版本 2'],['1','启用 · 版本 1']],uv):''}${x.tls?cfgInput('TLS 服务器名 SNI','sni',x.tls.server_name||''):''}</div>`}${cfgExisting(x)}`,!special)}
  if(cfg.tab==='routes')return cfgSection(`规则 ${cfg.index+1}`,`按顺序匹配 · 当前动作 ${x.outbound||x.action||'—'}`,`${cfgRouteForm(x)}<div class="config-secondary-actions"><button id="config-delete-rule" class="danger">删除此规则</button></div>${cfgExisting(x)}`);
  if(cfg.tab==='clients')return cfgSection(x.name,`用户状态：${x.enable?'已启用':'已停用'}`,`<p>显示名称：${esc(x.remark||x.name)}</p><p>流量上限：${x.volume?esc(bytes(x.volume)):'不限'}</p><div class="config-action-pair"><button data-cfg-action="${x.enable?'client_disable':'client_enable'}" class="secondary">${x.enable?'停用用户':'启用用户'}</button></div><p class="hint">用户配额与凭据请在 S-UI 编辑。</p>`,false);
  return ''
}
function cfgExisting(x){return `<details class="config-advanced"><summary>查看现有配置（凭据已隐藏）</summary><pre>${esc(JSON.stringify(cfgRedact(x),null,2))}</pre></details>`}
function cfgCreate(){const d=cfg.detail;
  if(cfg.tab==='inbounds'){const a=d.inbounds?.inbounds||[];return cfgSection('新增入站','按类型创建，或复制已有入站的复杂参数。',`${cfgSelect('创建方式','mode',[['new','按类型新建'],['copy','复制现有配置']],'new')}<div data-cfg-mode="copy" class="hidden">${cfgSelect('复制来源','source',a.map(x=>[x.tag,`${x.tag} · ${x.type}`]),a[0]?.tag)}</div><div data-cfg-mode="new">${cfgSelect('协议','type',[['vless','VLESS'],['trojan','Trojan'],['hysteria2','Hysteria2'],['tuic','TUIC'],['anytls','AnyTLS'],['mixed','Mixed'],['socks','SOCKS'],['http','HTTP']],'vless')}${cfgSelect('TLS 证书','tls',[['0','不使用 TLS'],...(d.tls_choices||[]).map(x=>[x.tag?'tag:'+x.tag:x.name?'name:'+x.name:'id:'+x.id,x.tag||x.name||'证书 #'+x.id])],'0')}</div><div class="config-fields">${cfgInput('新名称 / Tag','tag')}${cfgInput('监听地址','listen','::')}${cfgInput('监听端口','listen_port','','number')}${cfgInput('订阅公开地址','public_server')}${cfgInput('订阅公开端口','public_port','','number')}</div><p class="hint">复制时保留协议、TLS、传输设置，不复制已绑定用户。</p>`)}
  if(cfg.tab==='outbounds'){const a=d.outbounds?.outbounds||[];return cfgSection('新增出站','按协议填写，或复制已有完整配置。',`${cfgSelect('创建方式','mode',[['new','按类型新建'],['copy','复制现有配置']],'new')}<div data-cfg-mode="copy" class="hidden">${cfgSelect('复制来源','source',a.map(x=>[x.tag,`${x.tag} · ${x.type}`]),a[0]?.tag)}</div><div data-cfg-mode="new">${cfgSelect('类型','type',[['socks','SOCKS 代理'],['http','HTTP 代理'],['vless','VLESS'],['trojan','Trojan'],['hysteria2','Hysteria2'],['anytls','AnyTLS'],['direct','直连'],['block','阻断']],'socks')}</div><div class="config-fields">${cfgInput('新名称 / Tag','tag')}<div data-cfg-remote>${cfgInput('远端服务器','server')}${cfgInput('远端端口','server_port','','number')}</div><div data-cfg-auth>${cfgInput('用户名 / UUID','user')}${cfgInput('密码','password','','password')}</div><div data-cfg-socks>${cfgSelect('SOCKS 版本','version',[['5','SOCKS5'],['4','SOCKS4']],'5')}${cfgSelect('UDP over TCP','udp',[['off','禁用'],['2','启用 · 版本 2'],['1','启用 · 版本 1']],'off')}</div><div data-cfg-tls>${cfgInput('TLS 服务器名 SNI（可选）','sni')}</div></div>`)}
  if(cfg.tab==='routes')return cfgSection('新增路由规则','规则从上到下按顺序匹配。',`${cfgSelect('插入位置','position',[['first','最前面'],['last','最后面'],...(d.route_rules||[]).map((x,i)=>['before:'+i,`规则 ${i+1} 之前 · ${x.outbound||x.action||'—'}`])],'last')}${cfgRouteForm({action:'route',domain_suffix:[]})}`);
  if(cfg.tab==='clients')return cfgSection('创建用户','凭据自动生成；请选择允许使用的入站。',`<div class="config-fields">${cfgInput('用户名','name')}${cfgInput('显示名称','remark')}${cfgInput('流量上限 GB（0 为不限）','volume','0','number')}${cfgInput('到期日期（留空为不限）','expiry','','date')}</div><fieldset class="config-inbound-choice"><legend>允许使用的入站</legend>${(d.inbounds?.inbounds||[]).map(x=>`<label><input type="checkbox" data-cfg-inbound="${esc(x.id)}">${esc(x.tag)} · ${esc(x.type)}</label>`).join('')||'暂无入站'}</fieldset>`);
  return ''
}
function cfgCondition(key,value){return `<div class="config-condition">${cfgSelect('匹配字段','condition',cfgFields,key)}<label>匹配值（逗号或换行分隔）<textarea data-cfg-values rows="2">${esc(Array.isArray(value)?value.join('\n'):value??'')}</textarea></label><button data-cfg-remove class="text-button" aria-label="删除匹配条件">✕</button></div>`}
function cfgRouteForm(rule){const keys=cfgFields.map(x=>x[0]).filter(k=>k in rule),out=[...(cfg.detail.outbounds?.outbounds||[]),...(cfg.detail.endpoint_choices||[])].map(x=>[x.tag,`${x.tag} · ${x.type||'endpoint'}`]);if(cfg.add&&!keys.length)keys.push('domain_suffix');if(rule.outbound&&!out.some(x=>x[0]===rule.outbound))out.unshift([rule.outbound,rule.outbound]);return `<div id="config-conditions">${keys.map(k=>cfgCondition(k,rule[k])).join('')}</div><button id="config-add-condition" class="secondary">＋ 添加匹配条件</button><div class="config-fields">${cfgSelect('处理方式','action',[['route','走指定出站'],['reject','拒绝'],['hijack-dns','接管 DNS'],['sniff','嗅探协议']],rule.action||'route')}<div id="config-outbound-wrap">${cfgSelect('目标出站','outbound',out,rule.outbound||out[0]?.[0])}</div></div><p class="hint">未显示的高级字段（例如 sniffer）会保留。请在预览中核对规则顺序。</p>`}
function cfgVisibility(){const mode=cfgValue('mode')||'new',type=cfgValue('type'),show=(s,v)=>document.querySelectorAll(`#config-workspace ${s}`).forEach(x=>x.classList.toggle('hidden',!v));document.querySelectorAll('#config-workspace [data-cfg-mode]').forEach(x=>x.classList.toggle('hidden',x.dataset.cfgMode!==mode));show('[data-cfg-remote]',mode==='new'&&!['direct','block'].includes(type));show('[data-cfg-auth]',mode==='new'&&['socks','http','vless','trojan','hysteria2','anytls'].includes(type));show('[data-cfg-socks]',mode==='new'&&type==='socks');show('[data-cfg-tls]',mode==='new'&&['vless','trojan','hysteria2','anytls'].includes(type));show('#config-outbound-wrap',cfgValue('action')==='route')}
function cfgRule(){const rule=cfg.add?{}:structuredClone(cfgCurrent());for(const [key] of cfgFields)delete rule[key];let count=0;for(const row of document.querySelectorAll('#config-conditions .config-condition')){const key=row.querySelector('[data-cfg="condition"]').value,values=row.querySelector('[data-cfg-values]').value.split(/[\n,，]+/).map(x=>x.trim()).filter(Boolean);if(!values.length)throw Error('匹配值不能为空');if(key in rule)throw Error(`重复的匹配字段：${key}`);rule[key]=key==='port'?values.map(x=>{const n=Number(x);if(!Number.isInteger(n)||n<1||n>65535)throw Error('目标端口无效');return n}):values;count++}if(!count&&cfg.add)throw Error('请添加匹配条件');rule.action=cfgValue('action');if(rule.action==='route')rule.outbound=cfgRequired('outbound','目标出站');else delete rule.outbound;return rule}
function cfgRequest(force=''){const x=cfgCurrent(),r={server_ids:[cfg.id],action:force};if(['backup','restartSb'].includes(force))return r;
  if(cfg.tab==='inbounds'){r.action=cfg.add?'inbound_create':'inbound_patch';if(cfg.add){const tag=cfgRequired('tag','Tag'),listen=cfgRequired('listen','监听地址'),port=cfgPort('listen_port',true),pub=cfgValue('public_server'),pp=cfgPort('public_port');if(cfgValue('mode')==='copy'){r.source_tag=cfgRequired('source','复制来源');r.object_overrides={tag,listen,listen_port:port};if(pub)r.inbound_public_server=pub;r.inbound_public_port=pp||port}else{const type=cfgValue('type');r.object={type,tag,listen,listen_port:port,tls_id:0};if(pub){r.object.addrs=[{server:pub,server_port:pp||port}];r.object.out_json={type,server:pub,server_port:pp||port}}if(cfgValue('tls')!=='0')r.tls_ref=cfgValue('tls')}}else{r.inbound_tag=x.tag;const patch={},listen=cfgValue('listen'),port=cfgPort('listen_port'),pub=x.addrs?.[0]||x.out_json||{},server=cfgValue('public_server'),pp=cfgPort('public_port');if(listen!==String(x.listen||''))patch.listen=listen;if(port!==Number(x.listen_port||0))patch.listen_port=port;if(server&&server!==String(pub.server||''))r.inbound_public_server=server;if(pp&&pp!==Number(pub.server_port||0))r.inbound_public_port=pp;if(!Object.keys(patch).length&&!r.inbound_public_server&&!r.inbound_public_port)throw Error('没有发现变化');r.inbound_patch=patch}}
  else if(cfg.tab==='outbounds'){r.action=cfg.add?'outbound_create':'outbound_patch';if(cfg.add){const tag=cfgRequired('tag','Tag');if(cfgValue('mode')==='copy'){r.source_tag=cfgRequired('source','复制来源');r.object_overrides={tag}}else{const type=cfgValue('type'),o={type,tag};if(!['direct','block'].includes(type)){o.server=cfgRequired('server','远端服务器');o.server_port=cfgPort('server_port',true);const user=cfgValue('user'),password=cfgField('password')?.value||'';if(type==='socks'){o.version=cfgValue('version');if(user)o.username=user;if(password)o.password=password;const udp=cfgValue('udp');if(udp!=='off'){if(o.version!=='5')throw Error('UDP over TCP 仅支持 SOCKS5');o.udp_over_tcp={enabled:true,version:Number(udp)}}}else if(type==='http'){if(user)o.username=user;if(password)o.password=password}else if(type==='vless')o.uuid=user||cfgRequired('user','UUID');else o.password=password||cfgRequired('password','密码');if(['vless','trojan','hysteria2','anytls'].includes(type))o.tls={enabled:true,...(cfgValue('sni')?{server_name:cfgValue('sni')}:{})}}r.object=o}}else{r.object_tag=x.tag;const p={},host=cfgValue('server'),port=cfgPort('server_port'),user=cfgValue('user'),password=cfgField('password')?.value||'';if(host!==String(x.server||''))p.server=host;if(port!==Number(x.server_port||0))p.server_port=port;if(['socks','http','vless'].includes(x.type)&&user!==String(x.type==='vless'?x.uuid||'':x.username||''))p[x.type==='vless'?'uuid':'username']=user;if(password)p.password=password;if(x.type==='socks'){const udp=cfgValue('udp'),cur=x.udp_over_tcp,cv=cur===true?'2':cur?.enabled?String(cur.version||2):'off';if(udp!==cv)p.udp_over_tcp=udp==='off'?false:{enabled:true,version:Number(udp)}}if(x.tls&&cfgValue('sni')!==String(x.tls.server_name||''))p.tls={...x.tls,server_name:cfgValue('sni')};if(!Object.keys(p).length)throw Error('没有发现变化');r.object_patch=p}}
  else if(cfg.tab==='routes'){r.action=cfg.add?'route_rule_add':'route_rule_replace';r.route_rule=cfgRule();if(cfg.add){const pos=cfgValue('position');r.route_position=pos.startsWith('before:')?'before_index':pos;if(pos.startsWith('before:'))r.route_index=Number(pos.split(':')[1])}else r.route_index=cfg.index}
  else if(cfg.tab==='clients'){r.action=cfg.add?'client_create':force;if(cfg.add){const name=cfgRequired('name','用户名'),remark=cfgValue('remark')||name,volume=Number(cfgValue('volume')||'0'),expiry=cfgValue('expiry')?Math.floor(new Date(cfgValue('expiry')+'T23:59:59').getTime()/1000):0;if(!Number.isFinite(volume)||volume<0)throw Error('流量上限无效');const ids=[...document.querySelectorAll('[data-cfg-inbound]:checked')].map(n=>Number(n.dataset.cfgInbound));if(!ids.length)throw Error('请选择入站');const types=new Set((cfg.detail.inbounds?.inbounds||[]).filter(n=>ids.includes(n.id)).map(n=>n.type)),config={};for(const type of types){if(['vless','vmess'].includes(type))config[type]={name,uuid:crypto.randomUUID()};else if(type==='tuic')config[type]={name,uuid:crypto.randomUUID(),password:crypto.randomUUID().replaceAll('-','')};else if(['trojan','hysteria2','anytls','shadowsocks'].includes(type))config[type]={name,password:crypto.randomUUID().replaceAll('-','')};else throw Error(`${type} 用户请在 S-UI 创建`)}r.client={enable:true,name,remark,volume:Math.round(volume*1073741824),expiry,config};r.inbounds_by_server={[cfg.id]:ids}}else r.client_name=x.name}return r}
function cfgMessage(msg,bad=false){let el=$('config-message');if(!el){el=document.createElement('p');el.id='config-message';$('config-workspace').prepend(el)}el.className='config-message '+(bad?'error':'success');el.textContent=msg;el.scrollIntoView({block:'nearest'})}
async function cfgPreviewRequest(r){cfgResetPreview();const version=cfg.version,serverID=cfg.id,button=$('config-preview-button');if(button)button.disabled=true;try{const p=await api('operations/preview',{method:'POST',body:JSON.stringify(r)});if(version!==cfg.version||serverID!==cfg.id||!$('single-editor-dialog').open)return;cfg.preview=p;cfg.request=r;const c=p.changes?.[0];if(!c)throw Error('服务器没有返回预览结果');const before=typeof c.before==='string'?JSON.parse(c.before):c.before,after=typeof c.after==='string'?JSON.parse(c.after):c.after,box=document.createElement('div');box.id='config-preview';box.className='config-preview';box.innerHTML=`<div class="config-preview-head"><strong>变更预览</strong>${status(c.error?'不可执行':'可执行',c.error?'bad':'ok')}</div>${c.error?`<p class="error">${esc(c.error)}</p>`:`<p class="hint">请核对修改。执行前会备份 S-UI 数据库；预览有效期至 ${esc(date(p.expires))}。</p>${before||after?`<div class="config-diff-grid"><div><b>当前</b><pre>${esc(JSON.stringify(cfgRedact(before),null,2))}</pre></div><div><b>预期</b><pre>${esc(JSON.stringify(cfgRedact(after),null,2))}</pre></div></div>`:''}<button id="config-execute" class="primary">确认执行</button>`}`;$('config-workspace').appendChild(box);box.scrollIntoView({block:'nearest'})}catch(e){if(version===cfg.version&&serverID===cfg.id)cfgMessage('预览失败：'+e.message,true)}finally{if(button)button.disabled=false}}
async function cfgPreviewAction(force=''){try{await cfgPreviewRequest(cfgRequest(force))}catch(e){cfgMessage(e.message,true)}}
async function cfgExecute(){if(!cfg.preview)return;const button=$('config-execute');button.disabled=true;try{const result=await api('operations/execute',{method:'POST',body:JSON.stringify({preview_id:cfg.preview.id})}),row=result.results?.[0];if(!row?.ok)throw Error(row?.message||'执行失败');const tag=cfg.add?cfg.request.object?.tag||cfg.request.object_overrides?.tag||cfg.request.client?.name:null;cfg.detail=await api(`servers/${cfg.id}/detail`);cfg.add=false;const items=cfgList();cfg.index=tag?Math.max(0,items.findIndex(x=>(x.tag||x.name)===tag)):Math.min(cfg.index,Math.max(0,items.length-1));cfgRender();cfgMessage(`已保存并重新读取配置。${row.backup?'备份：'+row.backup:''}`);await refresh()}catch(e){cfgMessage('执行失败：'+e.message,true);button.disabled=false}}
$('close-editor').onclick=()=>$('single-editor-dialog').close();$('single-editor-dialog').addEventListener('close',()=>{cfg.id=null;cfgResetPreview()});
$('single-editor-dialog').addEventListener('click',e=>{const tab=e.target.closest('[data-cfg-tab]');if(tab){cfg.tab=tab.dataset.cfgTab;cfg.index=0;cfg.add=false;cfgRender();return}const item=e.target.closest('[data-cfg-index]');if(item){cfg.index=Number(item.dataset.cfgIndex);cfg.add=false;cfgRender();return}if(e.target.closest('#config-add')){cfg.add=true;cfgRender();return}if(e.target.closest('#config-preview-button')){cfgPreviewAction();return}if(e.target.closest('#config-execute')){cfgExecute();return}if(e.target.closest('#config-add-condition')){$('config-conditions').insertAdjacentHTML('beforeend',cfgCondition('domain_suffix',[]));cfgResetPreview();return}const remove=e.target.closest('[data-cfg-remove]');if(remove){remove.closest('.config-condition').remove();cfgResetPreview();return}if(e.target.closest('#config-delete-rule')){if(confirm(`预览删除规则 ${cfg.index+1}？`))cfgPreviewRequest({server_ids:[cfg.id],action:'route_rule_delete',route_index:cfg.index});return}const action=e.target.closest('[data-cfg-action]');if(action)cfgPreviewAction(action.dataset.cfgAction)});
$('single-editor-dialog').addEventListener('change',e=>{if(e.target.matches('[data-cfg]')){cfgVisibility();cfgResetPreview()}});
$('single-editor-dialog').addEventListener('input',e=>{if(e.target.matches('input,textarea'))cfgResetPreview()});
